.TH eph2eph "1" "May 2004" "eph2eph (ephemeris) 1.0" ephemeris.com
.SH NAME
eph2eph \- merges two JPL binary ephemeris files to a third
.SH SYNOPSIS
.B eph2eph
\fIinput1\fR \fIinput2\fR \fIoutput\fR [\fIstartJD \fR[\fIstopJD\fR]]
.br
.SH DESCRIPTION
.\" Add any additional description here
.PP
Merges two JPL binary ephemeris files into a third binary ephemeris file.
.TP
\fIinput1\fR
first binary ephemeris input file.
.TP
\fIinput2\fR
second binary ephemeris input file.
If \fIinput1\fR is the same as \fIinput2\fR,
.B eph2eph
will "scrub" the input ephemeris file to remove any inconsistencies.  (See
the intentional side effects mentioned below.)
.TP
\fIoutput\fR
the merged binary ephemeris file.
.TP
\fIstartJD\fR
optional Julian Day at which to begin (note that eph2eph
must begin at an integral ephemeris data block boundary of
typically 32 or 64 days, so
it will probably start soon before the desired \fIstartJD\fR).
If not specified, all of both input files are read.
.TP
\fIstopJD\fR
optional Julian Day at which to stop (note that eph2eph
must end at an integral ephemeris data block boundary of
typically 32 or 64 days, so
it will probably end soon after the desired \fIstopJD\fR).
If not specified, both input files are read to the end.
.PP
.B eph2eph
reads in two JPL binary ephemeris files and merges them into
a third binary ephemeris file.  The first two files must have the same
JPL ephemeris number, Earth-Moon Mass Ratio (EMRAT), distance of an AU
(in kilometers), number of constants in the header, and number of
coefficients in a data block.  Otherwise, they were not generated from
the same ephemeris and are not compatible.
.PP
The two input files must be adjacent in time, with either one ending
exactly where the other begins, or with some overlap between the end
of the first file and the beginning of the second.  Otherwise, there
would be a gap with unknown coefficients for a date span.
.PP
As an intentional side effect,
.B eph2eph
will remove several formatting errors in the original JPL files:
the last data block (a copy of the second to last block) is not repeated;
ASCII start and stop dates in the header are corrected;
ipt[*][0] and lpt[0] contain the next possible coefficient location
rather than 0 (this is the preferred format, as communicated by
JPL's Myles Standish to Paul Hardy); data in unused portions of the
header is set to all zeroes.
.SH AUTHOR
Written by Paul Hardy, ephemeris.com.
.SH "REPORTING BUGS"
Report bugs to <bugs@ephemeris.com>.
.SH COPYRIGHT
Copyright \(co 1994-2004 Paul Hardy
.PP
This is free software; you can redistribute it and/or modify it
under the terms of version 2.1 of the GNU Lesser General Public
License as published by the Free Software Foundation.
.PP
This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.
.PP
You should have received a copy of the GNU Lesser General Public
License along with this package; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
or see http://www.gnu.org/copyleft/lesser.html on the web.
.SH "SEE ALSO"
eph2asc(1), asc2eph(1), testeph(1), headcmp(1), ephcmp(1), ephcoeff(1),
vtransit(1)
